### ISSUE TITLE
Best way to contribute

### ISSUE THREAD

**Issue by mazondo** [Dashing-io/dashing#13]
I'm new to dashing and it's already deprecated!

Was wondering if there's a current state of the union for the fork, as well as if there's any guidelines on the best way to get involved and keep this thing going.

**Comment by tylermauthe** [comment]
Hello and welcome!

I very much appreciate your enthusiasm, we're definitely in need of assistance.

As a start, I've updated the [CONTRIBUTING.md](https://github.com/Dashing-io/dashing/blob/master/CONTRIBUTING.md).

I've also outlined a number of existing issues in this comment: https://github.com/Dashing-io/dashing/issues/8#issuecomment-240203263

There's also a call for a new homepage here: https://github.com/Dashing-io/dashing/issues/1

Any help with these items is appreciated! If you've got other ideas, create an issue and we can discuss. Thanks!
