### ISSUE TITLE
How do I start using this fork?

### ISSUE THREAD

**Issue by howardsternisbatman** [Dashing-io/dashing#14]
Hello,

How do I switch my current dashing install over to this fork? Sorry that's such a noob question I know.  So glad to see this project staying alive.

tx

**Comment by tylermauthe** [comment]
Hello! Great to see you again :smile: -- you've been a prolific Dashing user.

Unfortunately we haven't published this fork as a Gem, so it's not really easy to get started with it.

For existing projects, you can modify your Gemfile like so:
```ruby
gem 'dashing', :git => 'https://github.com/Dashing-io/dashing
```

Then doing a `bundle install` will pull in Dashing from this project. You can run dashing from your bundle with `bundle exec dashing` -- for example `bundle exec dashing generate job my_new_job`.

To install the command line gem takes a bit of tricky work and really there isn't a good answer. The best I could find is this:
http://stackoverflow.com/questions/2577346/how-to-install-gem-from-github-source

I've set aside a couple hours tomorrow to get this sorted.
