### ISSUE TITLE
Add a sidebar to Wiki

### ISSUE THREAD

**Issue by kinow** [Dashing-io/dashing#15]
At the moment whenever I want to find something I always have to skim through the Wiki pages to find the one I am after.

What others think about adding some categories in a Sidebar?

I was playing with Wiki sidebars, but not sure if we want that many sub-levels: https://github.com/kinow/dashing/wiki

Thoughts?

**Comment by tylermauthe** [comment]
I like it, good idea.

**Comment by kinow** [comment]
Initial version done!

https://github.com/Dashing-io/dashing/wiki

Moved all How Tos under a single "How To" category. We can sort out a better way later, but at least now we can have some hierarchy in place.

**Comment by tylermauthe** [comment]
Woot!
