### ISSUE TITLE
Make the the github origanization public.

### ISSUE THREAD

**Issue by geoaxis** [Dashing-io/dashing#4]
The current Dashing-io organisation on github has no public members. 

I strongly believe that if this project is to exist and thrive outside of the organisation it was forked from then it must be opened up and have public members.

**Comment by kinow** [comment]
As far as I know users must make it public or not, and not the organisation. I think it is to preserve privacy of members.

See  https://help.github.com/articles/publicizing-or-hiding-organization-membership/

Not sure if there is a way for the organisation to publicize all its members. Guess it would be bad for privacy perhaps?

**Comment by kinow** [comment]
Thanks for the invite to become part of the organisation. I had a look, and couldn't find anything to make everyone public in the organisation. @geoaxis I see you there as a member too and have already publicized your membership :-)

So I'm closing this issue, but should you find we sill have to work on this, feel free to re-open it.
