### ISSUE TITLE
Install dashing gem on centos

### ISSUE THREAD

**Issue by trekr5** [Dashing-io/dashing#6]
Hello,

When I try to install dashing gem on Centos or Amazon Linux using gem install dashing. I get the following error:-

    ERROR:  Error installing dashing:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9 extconf.rb
       mkmf.rb can't find header files for ruby at /usr/share/ruby/include/ruby.h

     Gem files will remain installed in /usr/local/share/gems1.9/gems/eventmachine-1.2.0.1 for inspection.
     Results logged to /usr/local/share/gems1.9/gems/eventmachine-1.2.0.1/ext/gem_make.out
     [root@ip-10-0-107-75 chef]# gem install dashing -v 1.3.4
     Building native extensions.  This could take a while...
     ERROR:  Error installing dashing:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9 extconf.rb
     mkmf.rb can't find header files for ruby at /usr/share/ruby/include/ruby.h

     Gem files will remain installed in /usr/local/share/gems1.9/gems/eventmachine-1.2.0.1 for inspection.

I've tried installing yum install gcc gcc-c++ make openssl-devel (which is the equivalent of installing build-essential on Ubuntu) and sudo yum install -y libxml2 libxml2-devel libxslt libxslt-devel (which installs the equivalent of libssldev-install on Ubuntu) before attempting to install the dashing gem (version 1.3.4 or 1.3.7) without success.

Can dashing run on other linux distro besides Ubuntu? If so how can I make dashing install?

Thanks

**Comment by trekr5** [comment]
Hi Bruno,

I installed ruby-devel using yum install "ruby-devel" and then tried to do a gem install dashing and still received the same error. 

What other packages did you install?

Thanks,

**Comment by kinow** [comment]
I documented everything in the internal Wiki, but I'm attending a workshop now, with no VPN access. I can confirm on Monday (NZ time), but IIRC, I used a few links I found, while troubleshooting installing ruby and the gems.

The one that I have in my bookmark is: http://arstechnica.com/civis/viewtopic.php?f=16&t=1239329

I think the 4th comment helped me. Take a look if you are missing any of these packages, and if that works for you, feel free to close the ticket and also comment how you fixed :-) so we can save other people (and maybe ourselves in the future) when installing Dashing.

ps: I'm building a few RPM's at work, and may have to build one for dashing too. Maybe we can include an official RPM in the future too

**Comment by trekr5** [comment]
Hello,

I've fixed it with the help of the above post.

I'm putting the steps here in case someone else has the same problem:

1) yum install gcc gcc-c++ make rubygem-bundler openssl-devel libxml2 libxml2-devel libxslt libxslt-devel zlib zlib-devel ruby-devel scl-utils scl-utils-build
2) enable epel repo 
3) install ruby 2.3.0 and rvm (ruby version switch):
    command curl -sSL https://rvm.io/mpapis.asc | sudo gpg2 --import -
    curl -sSL https://get.rvm.io | bash -s stable --ruby
    source /usr/local/rvm/scripts/rvm
    rvm use ruby-2.3.0

4) gem install dashing --no-rdoc --no-ri
5) dashing new new_dashboard_name
6) chmod 777 new_dashboard_name
7) cd new_dashboard_name
8) ....
